# Generated by Django 4.0.3 on 2022-04-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
