# Generated by Django 4.0.3 on 2022-04-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('descrption', models.TextField(blank=True, max_length=200, null=True)),
                ('linkto', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
