# Generated by Django 4.0.3 on 2022-04-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_explore'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
