# Generated by Django 4.0.3 on 2022-04-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_explore_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hour', models.IntegerField()),
                ('numbers_student', models.IntegerField()),
                ('numbers_staff', models.IntegerField()),
                ('college_allumn', models.IntegerField()),
            ],
        ),
    ]
