# Generated by Django 4.0.3 on 2022-04-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_collage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage',
            name='college_allumn',
        ),
    ]
