# Generated by Django 4.0.3 on 2022-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_rename_collage_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hours', models.IntegerField()),
                ('number_students', models.IntegerField()),
                ('number_staff', models.IntegerField()),
                ('number_allumn', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
